// HAN — UI copy, four languages.
//
// Lifted verbatim from the prototype's two message dictionaries so the wording
// is byte-identical to what was reviewed on screen. The tone is a product
// decision, not filler: direct, in the trader's own register, money language
// rather than report-card language (handoff §7).
//
// W = the buyer-surface strings. F = filters, panels and tools.
// Turkish is the source language; every key carries all four.

import type { Lang } from "@/data/types";

export type CopyEntry = { tr: string; en: string; ru: string; ar: string };

/** Buyer surface: sections, search, store panel, plan, map, account. */
export const W_COPY: Record<string, CopyEntry> = {
  search: { tr: "Ara", en: "Search", ru: "Искать", ar: "ابحث" },
  searchPh: { tr: "Ürün, kategori, dükkân, kapı no veya telefon", en: "Product, category, shop, door no or phone", ru: "Товар, категория, магазин, номер двери или телефон", ar: "منتج أو فئة أو متجر أو رقم باب أو هاتف" },
  secDiscover: { tr: "Keşfet", en: "Discover", ru: "Обзор", ar: "استكشاف" },
  secSearch: { tr: "Ara", en: "Search", ru: "Поиск", ar: "بحث" },
  secCats: { tr: "Kategoriler", en: "Categories", ru: "Категории", ar: "الفئات" },
  secPlan: { tr: "Plan", en: "Plan", ru: "План", ar: "الخطة" },
  secMap: { tr: "Harita", en: "Map", ru: "Карта", ar: "الخريطة" },
  secEvents: { tr: "Etkinlikler", en: "Events", ru: "События", ar: "الفعاليات" },
  allCats: { tr: "Tüm kategoriler", en: "All categories", ru: "Все категории", ar: "كل الفئات" },
  featured: { tr: "Öne çıkan dükkânlar", en: "Featured shops", ru: "Избранные магазины", ar: "متاجر مميزة" },
  shopsWord: { tr: "dükkân", en: "shops", ru: "магазинов", ar: "متجرًا" },
  from: { tr: "başlangıç", en: "from", ru: "от", ar: "من" },
  products: { tr: "Ürünler ve fiyatlar", en: "Products and prices", ru: "Товары и цены", ar: "المنتجات والأسعار" },
  certs: { tr: "Sertifikalar", en: "Certificates", ru: "Сертификаты", ar: "الشهادات" },
  addPlan: { tr: "Plana ekle", en: "Add to plan", ru: "Добавить в план", ar: "أضف إلى الخطة" },
  streetPage: { tr: "Sokak sayfası", en: "Street page", ru: "Страница улицы", ar: "صفحة الشارع" },
  directions: { tr: "Yol tarifi al", en: "Get directions", ru: "Маршрут", ar: "الاتجاهات" },
  save: { tr: "Kaydet", en: "Save", ru: "Сохранить", ar: "حفظ" },
  unsave: { tr: "Kayıttan çıkar", en: "Remove", ru: "Убрать", ar: "إزالة" },
  close: { tr: "Kapat", en: "Close", ru: "Закрыть", ar: "إغلاق" },
  pickTitle: { tr: "Bir dükkân seçin", en: "Pick a shop", ru: "Выберите магазин", ar: "اختر متجرًا" },
  pickBody: { tr: "Soldaki listeden bir kayda dokunun; ürünler, fiyatlar ve ticari bilgiler burada açılır.", en: "Tap a record in the list; products, prices and trade details open here.", ru: "Выберите запись слева — товары, цены и условия появятся здесь.", ar: "اختر سجلاً من القائمة؛ تظهر المنتجات والأسعار والتفاصيل هنا." },
  noResTitle: { tr: "Sonuç bulunamadı", en: "No results", ru: "Ничего не найдено", ar: "لا نتائج" },
  noResBody: { tr: "Ürün adıyla aramayı deneyin ya da soldaki filtreleri gevşetin.", en: "Try searching by product name or loosen the filters on the left.", ru: "Попробуйте искать по названию товара или ослабьте фильтры слева.", ar: "جرّب البحث باسم المنتج أو خفّف المرشحات على اليسار." },
  loosenBody: { tr: "Filtreler olmadan %s dükkân çıkıyor.", en: "Without the filters this search finds %s shops.", ru: "Без фильтров находится %s магазинов.", ar: "بدون المرشحات يظهر %s متجرًا." },
  idleTitle: { tr: "Ne arıyorsunuz?", en: "What are you looking for?", ru: "Что вы ищете?", ar: "عمّاذا تبحث؟" },
  idleBody: { tr: "Ürün adı, kategori, dükkân adı, kapı numarası ya da telefon yazabilirsiniz.", en: "Type a product, a category, a shop name, a door number or a phone.", ru: "Введите товар, категорию, название магазина, номер двери или телефон.", ar: "اكتب منتجًا أو فئة أو اسم متجر أو رقم باب أو هاتفًا." },
  didYouMean: { tr: "Şunu mu demek istediniz:", en: "Did you mean:", ru: "Вы имели в виду:", ar: "هل تعني:" },
  subcats: { tr: "Alt kategoriler", en: "Sub-categories", ru: "Подкатегории", ar: "الفئات الفرعية" },
  planTitle: { tr: "Alışveriş planı", en: "Shopping plan", ru: "План покупок", ar: "خطة التسوق" },
  planSub: { tr: "Alım listeniz yer bazlı duraklara bölünür, varış saatleri ve kapanış riski hesaplanır.", en: "Your buying list is split into stops by place, with arrival times and closing risk.", ru: "Список покупок разбивается на точки с временем прибытия и риском закрытия.", ar: "تُقسَّم قائمة الشراء إلى محطات مع أوقات الوصول ومخاطر الإغلاق." },
  stops: { tr: "Duraklar", en: "Stops", ru: "Остановки", ar: "المحطات" },
  itemsHere: { tr: "Burada alacaklarınız", en: "What you buy here", ru: "Что купить здесь", ar: "ما تشتريه هنا" },
  shopsHere: { tr: "Dükkânlar", en: "Shops", ru: "Магазины", ar: "المتاجر" },
  listTitle: { tr: "Alım listesi", en: "Buying list", ru: "Список покупок", ar: "قائمة الشراء" },
  fName: { tr: "Ürün", en: "Item", ru: "Товар", ar: "منتج" },
  fQty: { tr: "Adet", en: "Qty", ru: "Кол-во", ar: "الكمية" },
  fTarget: { tr: "Hedef ₺", en: "Target ₺", ru: "Цель ₺", ar: "الهدف ₺" },
  addRow: { tr: "Satır ekle", en: "Add line", ru: "Добавить строку", ar: "أضف سطرًا" },
  delete: { tr: "Sil", en: "Delete", ru: "Удалить", ar: "حذف" },
  eName: { tr: "Ürün adı gerekli", en: "Item name is required", ru: "Нужно название", ar: "اسم المنتج مطلوب" },
  planEmpty: { tr: "Plan için listeye kalem ekleyin", en: "Add lines to build a plan", ru: "Добавьте строки, чтобы построить план", ar: "أضف بنودًا لبناء خطة" },
  planEmptyBody: { tr: "Sağdaki forma ne alacağınızı yazın; duraklar ve rota kendiliğinden kurulur.", en: "Write what you need in the form on the right; stops and the route build themselves.", ru: "Заполните форму справа — точки и маршрут построятся сами.", ar: "اكتب ما تحتاجه في النموذج؛ تُبنى المحطات والمسار تلقائيًا." },
  seeOnMap: { tr: "Rotayı haritada gör", en: "See the route on the map", ru: "Маршрут на карте", ar: "شاهد المسار على الخريطة" },
  mapTitle: { tr: "Harita", en: "Map", ru: "Карта", ar: "الخريطة" },
  mapSub: { tr: "Hanlar ve çarşı bölgeleri gerçek konumlarında; planınız varsa duraklar sırayla numaralanır.", en: "Hans and bazaar areas at their real locations; if you have a plan, stops are numbered in order.", ru: "Ханы и районы базара на своих местах; если есть план, точки нумеруются по порядку.", ar: "الخانات ومناطق السوق في مواقعها الحقيقية؛ وإن كانت لديك خطة تُرقَّم المحطات بالترتيب." },
  mapAll: { tr: "Tüm çarşı", en: "Whole bazaar", ru: "Весь базар", ar: "كل السوق" },
  mapRoute: { tr: "Planımın rotası", en: "My plan route", ru: "Мой маршрут", ar: "مسار خطتي" },
  noEvents: { tr: "Bu türde etkinlik yok", en: "No events of this kind", ru: "Нет таких событий", ar: "لا توجد أنشطة من هذا النوع" },
  noEventsBody: { tr: "Filtreyi “Tümü” yapıp takvimin tamamına bakın.", en: "Switch the filter to “All” to see the whole calendar.", ru: "Выберите «Все», чтобы увидеть весь календарь.", ar: "اختر «الكل» لعرض التقويم بالكامل." },
  addedPlan: { tr: "Listeye eklendi", en: "Added to the list", ru: "Добавлено в список", ar: "أُضيف إلى القائمة" },
  sortLbl: { tr: "Sıralama: %s", en: "Sorted by %s", ru: "Сортировка: %s", ar: "الترتيب: %s" },
  openNow: { tr: "Açık", en: "Open", ru: "Открыто", ar: "مفتوح" },
  closedNow: { tr: "Kapalı", en: "Closed", ru: "Закрыто", ar: "مغلق" },
  hours: { tr: "Bugün", en: "Today", ru: "Сегодня", ar: "اليوم" },
  minOrder: { tr: "Min. sipariş", en: "Min. order", ru: "Мин. заказ", ar: "أدنى طلب" },
  respShort: { tr: "yanıt %s dk", en: "%s min reply", ru: "ответ %s мин", ar: "رد %s د" },
  doorNo: { tr: "No", en: "No", ru: "№", ar: "رقم" },
  lead: { tr: "Teslim süresi", en: "Lead time", ru: "Срок", ar: "مدة التسليم" },
  langs: { tr: "Konuşulan dil", en: "Languages", ru: "Языки", ar: "اللغات" },
  days: { tr: "gün", en: "days", ru: "дн.", ar: "يوم" },
  auOpen: { tr: "Hesap", en: "Account", ru: "Аккаунт", ar: "الحساب" },
  auGuestTitle: { tr: "Misafir olarak geziyorsunuz", en: "You are browsing as a guest", ru: "Вы гость", ar: "أنت تتصفّح كزائر" },
  auGuestSub: { tr: "Her şey girişsiz çalışır. Hesap yalnızca işinizi cihazlar arasında taşır.", en: "Everything works without signing in. An account only carries your work between devices.", ru: "Всё работает без входа. Аккаунт лишь переносит вашу работу между устройствами.", ar: "كل شيء يعمل بدون تسجيل. الحساب ينقل عملك بين الأجهزة فقط." },
  auR1: { tr: "Aynı iş, başka cihaz", en: "Same work, another device", ru: "Та же работа, другое устройство", ar: "العمل نفسه على جهاز آخر" },
  auR1b: { tr: "Çarşıda telefonda kurduğunuz rota, otelde masaüstünde açılır.", en: "The route you build on your phone opens on your laptop at the hotel.", ru: "Маршрут с телефона откроется на ноутбуке в отеле.", ar: "المسار الذي تبنيه على هاتفك يُفتح على حاسبك في الفندق." },
  auR2: { tr: "Teklif geldiğinde haber", en: "Told when an offer lands", ru: "Уведомление о предложении", ar: "إشعار عند وصول عرض" },
  auR2b: { tr: "Talebinize dükkân fiyat verdiğinde bildirim alırsınız.", en: "You get a notice when a shop quotes your request.", ru: "Вы получите уведомление, когда магазин ответит.", ar: "تصلك رسالة عندما يسعّر متجر طلبك." },
  auR3: { tr: "Kayıtlı arama ve koleksiyonlar", en: "Saved searches and collections", ru: "Сохранённые поиски и коллекции", ar: "بحوث محفوظة ومجموعات" },
  auR3b: { tr: "Aynı aramayı bir daha kurmayın; yeni dükkân çıkınca haber verir.", en: "Never rebuild the same search; new shops in it find you.", ru: "Не собирайте один и тот же поиск заново.", ar: "لا تعِد بناء البحث نفسه." },
  auContactLbl: { tr: "Telefon veya e-posta", en: "Phone or email", ru: "Телефон или эл. почта", ar: "هاتف أو بريد" },
  auContactHint: { tr: "Tek kullanımlık kod göndeririz. Şifre yok.", en: "We send a one-time code. No password.", ru: "Пришлём одноразовый код. Без пароля.", ar: "نرسل رمزًا لمرة واحدة. بلا كلمة مرور." },
  auContactPh: { tr: "905xxxxxxxxx veya ad@ornek.com", en: "+90 5xx xxx xx xx or you@example.com", ru: "+90 5xx… или you@example.com", ar: "905xxxxxxxxx أو you@example.com" },
  auContactErr: { tr: "Geçerli bir telefon ya da e-posta yazın", en: "Enter a valid phone or email", ru: "Введите телефон или эл. почту", ar: "أدخل هاتفًا أو بريدًا صحيحًا" },
  auSend: { tr: "Kod gönder", en: "Send the code", ru: "Отправить код", ar: "أرسل الرمز" },
  auStayGuest: { tr: "Misafir olarak devam et", en: "Continue as a guest", ru: "Продолжить как гость", ar: "أكمل كزائر" },
  auCodeTitle: { tr: "Kodu girin", en: "Enter the code", ru: "Введите код", ar: "أدخل الرمز" },
  auCodeSent: { tr: "%s adresine dört haneli bir kod gönderdik.", en: "We sent a four-digit code to %s.", ru: "Мы отправили четырёхзначный код на %s.", ar: "أرسلنا رمزًا من أربعة أرقام إلى %s." },
  auCodeLbl: { tr: "Doğrulama kodu", en: "Verification code", ru: "Код подтверждения", ar: "رمز التحقق" },
  auCodeHint: { tr: "Bu prototipte dört haneli her kod geçer.", en: "In this prototype any four digits work.", ru: "В прототипе подходит любой код из 4 цифр.", ar: "في هذا النموذج يصلح أي أربعة أرقام." },
  auCodeErr: { tr: "Dört haneli kodu girin", en: "Enter the four-digit code", ru: "Введите код из 4 цифр", ar: "أدخل الرمز المكوّن من أربعة أرقام" },
  auVerify: { tr: "Doğrula ve gir", en: "Verify and continue", ru: "Подтвердить и войти", ar: "تحقّق وادخل" },
  auBack: { tr: "Geri", en: "Back", ru: "Назад", ar: "رجوع" },
  auNameLbl: { tr: "Adınız", en: "Your name", ru: "Ваше имя", ar: "اسمك" },
  auNamePh: { tr: "Dükkâna böyle görünür", en: "This is how shops see you", ru: "Так вас видят магазины", ar: "هكذا تراك المتاجر" },
  auProfileTitle: { tr: "Hesabınız", en: "Your account", ru: "Ваш аккаунт", ar: "حسابك" },
  auProfileSub: { tr: "Bu cihazdaki işler hesabınıza bağlı.", en: "The work on this device is tied to your account.", ru: "Работа на этом устройстве привязана к аккаунту.", ar: "أعمال هذا الجهاز مرتبطة بحسابك." },
  auSynced: { tr: "Eşitlendi", en: "Synced", ru: "Синхронизировано", ar: "متزامن" },
  auCountryLbl: { tr: "Ülke", en: "Country", ru: "Страна", ar: "الدولة" },
  auCountryHint: { tr: "Nakliye ve tax-free hesapları buradan gelir.", en: "Freight and tax-free figures come from this.", ru: "Отсюда берутся расчёты фрахта и tax-free.", ar: "منها تُحسب الشحن والإعفاء الضريبي." },
  auCatsLbl: { tr: "İlgilendiğiniz kategoriler", en: "Categories you buy", ru: "Интересующие категории", ar: "الفئات التي تشتريها" },
  auCatsHint: { tr: "Keşfet sayfası ve bildirimler bunlara göre sıralanır.", en: "Discover and your notices order themselves around these.", ru: "По ним сортируются «Обзор» и уведомления.", ar: "تُرتَّب صفحة الاستكشاف والإشعارات وفقها." },
  auCompanyLbl: { tr: "Firma", en: "Company", ru: "Компания", ar: "الشركة" },
  auTaxLbl: { tr: "Vergi no", en: "Tax ID", ru: "ИНН", ar: "الرقم الضريبي" },
  auSave: { tr: "Kaydet", en: "Save", ru: "Сохранить", ar: "حفظ" },
  auSaved: { tr: "Hesap güncellendi", en: "Account updated", ru: "Аккаунт обновлён", ar: "تم تحديث الحساب" },
  auSignOut: { tr: "Çıkış yap", en: "Sign out", ru: "Выйти", ar: "خروج" },
  auSignedOut: { tr: "Çıkış yapıldı — listeleriniz bu cihazda kaldı", en: "Signed out — your lists stayed on this device", ru: "Вы вышли — списки остались на устройстве", ar: "تم الخروج — بقيت قوائمك على الجهاز" },
  auWelcome: { tr: "Hoş geldiniz", en: "Welcome", ru: "Добро пожаловать", ar: "مرحبًا" },
  auCarried: { tr: "%s kayıt hesabınıza taşındı", en: "%s records carried into your account", ru: "%s записей перенесено в аккаунт", ar: "نُقل %s سجلًا إلى حسابك" },
  auStatSaved: { tr: "Kayıtlı dükkân", en: "Saved shops", ru: "Сохранённые магазины", ar: "متاجر محفوظة" },
  auStatList: { tr: "Alım listesi", en: "Buying list", ru: "Список закупки", ar: "قائمة الشراء" },
  auStatReq: { tr: "Talep", en: "Requests", ru: "Запросы", ar: "الطلبات" },
  auSellerTitle: { tr: "Ben esnafım", en: "I run a shop", ru: "У меня есть магазин", ar: "أنا صاحب متجر" },
  auSellerSub: { tr: "Dükkânınızı rehbere ekleyin, talepleri alın.", en: "Add your shop to the guide and receive requests.", ru: "Добавьте магазин в справочник и получайте заявки.", ar: "أضف متجرك إلى الدليل واستلم الطلبات." },
  auEsnafIntro: { tr: "Üç satır yeter. Ekibimiz dükkânı yerinde doğrular, sonra panelinize giriş açılır.", en: "Three lines is enough. Our team verifies the shop on site, then your panel opens.", ru: "Достаточно трёх строк. Команда проверит магазин на месте, затем откроется панель.", ar: "ثلاثة أسطر تكفي. يتحقّق فريقنا من المتجر ميدانيًا ثم تُفتح لوحتك." },
  auEsShop: { tr: "Dükkân adı", en: "Shop name", ru: "Название магазина", ar: "اسم المتجر" },
  auEsShopPh: { tr: "Tabelada ne yazıyor", en: "What the sign says", ru: "Как на вывеске", ar: "ما هو مكتوب على اللوحة" },
  auEsPlace: { tr: "Han / sokak ve kapı no", en: "Han / street and door no", ru: "Хан / улица и номер", ar: "الخان / الشارع ورقم الباب" },
  auEsPlacePh: { tr: "Yıldız Han, 2. kat, no 118", en: "Yıldız Han, floor 2, no 118", ru: "Йылдыз Хан, 2 этаж, № 118", ar: "خان يلدز، الطابق ٢، رقم ١١٨" },
  auEsTel: { tr: "Telefon", en: "Phone", ru: "Телефон", ar: "هاتف" },
  auEsSend: { tr: "Kaydı gönder", en: "Send the listing", ru: "Отправить заявку", ar: "أرسل التسجيل" },
  auEsnafSent: { tr: "Kaydınız alındı", en: "Your listing was received", ru: "Заявка получена", ar: "تم استلام تسجيلك" },
  auEsnafOkTitle: { tr: "Kaydınız kuyruğa girdi", en: "Your listing is in the queue", ru: "Заявка в очереди", ar: "تسجيلك في قائمة الانتظار" },
  auEsnafOkBody: { tr: "Saha ekibi iki iş günü içinde dükkânı doğrular. Doğrulandığında satıcı panelinize giriş bağlantısı gelir.", en: "The field team verifies the shop within two working days. Once verified you get a link to your seller panel.", ru: "Команда проверит магазин в течение двух рабочих дней, затем пришлём ссылку на панель продавца.", ar: "يتحقّق الفريق الميداني خلال يومي عمل، ثم يصلك رابط لوحة البائع." },
  auReq: { tr: "Bu alan gerekli", en: "This field is required", ru: "Обязательное поле", ar: "هذا الحقل مطلوب" },
  auTelErr: { tr: "Geçerli bir telefon yazın", en: "Enter a valid phone", ru: "Введите телефон", ar: "أدخل هاتفًا صحيحًا" },
  skip: { tr: "İçeriğe geç", en: "Skip to content", ru: "Перейти к содержимому", ar: "انتقل إلى المحتوى" },
  copyLink: { tr: "Bu görünümün bağlantısını kopyala", en: "Copy a link to this view", ru: "Скопировать ссылку на этот вид", ar: "انسخ رابط هذا العرض" },
  linkCopied: { tr: "Bağlantı kopyalandı", en: "Link copied", ru: "Ссылка скопирована", ar: "تم نسخ الرابط" },
  offline: { tr: "Çevrimdışısınız. Kayıtlı dükkânlarınız, planınız ve alım listeniz açılır; arama sonuçları ve kurlar güncellenmez.", en: "You are offline. Saved shops, your plan and buying list still open; search results and rates are not refreshed.", ru: "Вы офлайн. Сохранённые магазины, план и список открываются; результаты поиска и курсы не обновляются.", ar: "أنت غير متصل. تُفتح المتاجر المحفوظة وخطتك وقائمتك؛ ولا تُحدَّث نتائج البحث والأسعار." },
  matches: { tr: "%s dükkân eşleşti", en: "%s shops matched", ru: "%s магазинов найдено", ar: "%s متجرًا مطابقًا" },
  noMatch: { tr: "Eşleşme yok", en: "No match", ru: "Нет совпадений", ar: "لا تطابق" }
};

/** Filters, right-hand panels, requests, saved, tools. */
export const F_COPY: Record<string, CopyEntry> = {
  sort: { tr: "Sıralama", en: "Sort by", ru: "Сортировка", ar: "الترتيب" },
  trade: { tr: "Alışveriş türü", en: "Buying type", ru: "Тип покупки", ar: "نوع الشراء" },
  area: { tr: "Semt", en: "District", ru: "Район", ar: "المنطقة" },
  flags: { tr: "Ticari özellikler", en: "Trade features", ru: "Особенности", ar: "مزايا تجارية" },
  clear: { tr: "Filtreleri temizle", en: "Clear filters", ru: "Сбросить фильтры", ar: "مسح المرشحات" },
  all: { tr: "Tümü", en: "All", ru: "Все", ar: "الكل" },
  sNear: { tr: "En yakın", en: "Nearest", ru: "Ближайшие", ar: "الأقرب" },
  sPrice: { tr: "Uygun fiyat", en: "Lowest price", ru: "Дешевле", ar: "الأرخص" },
  sRating: { tr: "Yüksek puan", en: "Top rated", ru: "Высокий рейтинг", ar: "الأعلى تقييمًا" },
  sFresh: { tr: "Yeni güncellenen", en: "Recently updated", ru: "Недавно обновлённые", ar: "المحدَّث حديثًا" },
  wholesale: { tr: "Toptan", en: "Wholesale", ru: "Опт", ar: "جملة" },
  retail: { tr: "Perakende", en: "Retail", ru: "Розница", ar: "تجزئة" },
  fOpen: { tr: "Şu an açık", en: "Open now", ru: "Открыто сейчас", ar: "مفتوح الآن" },
  fTaxFree: { tr: "Tax-free", en: "Tax-free", ru: "Tax-free", ar: "إعفاء ضريبي" },
  fProducer: { tr: "Üretici", en: "Producer", ru: "Производитель", ar: "منتج" },
  fCert: { tr: "Sertifikalı", en: "Certified", ru: "Сертифицирован", ar: "معتمد" },
  fMoq: { tr: "Düşük minimum", en: "Low minimum", ru: "Низкий минимум", ar: "حد أدنى منخفض" },
  fExport: { tr: "Yurt dışı gönderim", en: "Ships abroad", ru: "Отправка за рубеж", ar: "شحن للخارج" },
  fCustoms: { tr: "Gümrük desteği", en: "Customs support", ru: "Помощь с таможней", ar: "دعم جمركي" },
  hmResume: { tr: "Kaldığın yer", en: "Where you left off", ru: "Где вы остановились", ar: "من حيث توقفت" },
  hmResumeSub: { tr: "Devam eden işlerin", en: "Your open work", ru: "Ваши текущие дела", ar: "أعمالك الجارية" },
  hmStart: { tr: "Bugün ne yapıyorsun?", en: "What are you doing today?", ru: "Чем займётесь сегодня?", ar: "ماذا ستفعل اليوم؟" },
  hmStartSub: { tr: "Çarşıya nereden başlayalım", en: "Pick where the bazaar starts", ru: "С чего начнём базар", ar: "من أين نبدأ السوق" },
  kPlan: { tr: "%s kalem hazır", en: "%s items ready", ru: "%s позиций готово", ar: "%s بندًا جاهز" },
  kPlanSub: { tr: "Duraklara bölünmüş rotayı gör", en: "See the route split into stops", ru: "Маршрут по точкам", ar: "شاهد المسار مقسّمًا" },
  kSaved: { tr: "%s dükkân kayıtlı", en: "%s shops saved", ru: "Сохранено %s магазинов", ar: "%s متجرًا محفوظ" },
  kSavedSub: { tr: "Aramada filtreleyerek geri dönün", en: "Filter the search to come back to them", ru: "Вернитесь к ним через поиск", ar: "عد إليها من البحث" },
  kEvent: { tr: "%s etkinlik rotanızda", en: "%s events on your route", ru: "%s событий в маршруте", ar: "%s نشاطًا في مسارك" },
  kEventSub: { tr: "Saatleri sabit — plana göre sıralayın", en: "Fixed times — order the plan around them", ru: "Фиксированное время", ar: "مواعيد ثابتة" },
  sWalk: { tr: "Gez", en: "Explore", ru: "Прогулка", ar: "تجوّل" },
  sWalkSub: { tr: "Haritada hanları ve bölgeleri gör", en: "See hans and areas on the map", ru: "Ханы и районы на карте", ar: "شاهد الخانات والمناطق" },
  sFind: { tr: "Ara", en: "Search", ru: "Поиск", ar: "بحث" },
  sFindSub: { tr: "Ürün, kategori veya dükkân bul", en: "Find a product, category or shop", ru: "Найдите товар, категорию или магазин", ar: "ابحث عن منتج أو فئة أو متجر" },
  sBuy: { tr: "Toptan al", en: "Buy wholesale", ru: "Оптовая закупка", ar: "شراء بالجملة" },
  sBuySub: { tr: "Alım listesi yap, planı kur", en: "Make a buying list, build the plan", ru: "Составьте список и план", ar: "أعدّ قائمة وابنِ الخطة" },
  catTitle: { tr: "Sana göre kategoriler", en: "Categories for you", ru: "Категории для вас", ar: "فئات تناسبك" },
  catSub: { tr: "Geçmişin, kayıtların ve listenden", en: "From your history, saves and list", ru: "Из истории, сохранённого и списка", ar: "من سجلك ومحفوظاتك وقائمتك" },
  whyList: { tr: "Listende var", en: "On your list", ru: "В вашем списке", ar: "في قائمتك" },
  whySaved: { tr: "Kayıtlı dükkânından", en: "From a saved shop", ru: "Из сохранённого магазина", ar: "من متجر محفوظ" },
  whyCommon: { tr: "Çarşıda yaygın", en: "Common in the bazaar", ru: "Часто на базаре", ar: "شائع في السوق" },
  brTitle: { tr: "Kategoriler", en: "Categories", ru: "Категории", ar: "الفئات" },
  brSub: { tr: "Ana gruptan kategoriye, kategoriden alt kategoriye — grup şeridi üstte, seçtiğiniz kategori sağda açılır", en: "Main group to category to sub-category — the group strip sits on top, your pick opens on the right", ru: "Группа → категория → подкатегория: полоса групп сверху, выбранное открывается справа", ar: "المجموعة ثم الفئة ثم الفئة الفرعية — شريط المجموعات أعلى، واختيارك يُفتح على اليمين" },
  cgWhere: { tr: "Bu iş hangi sokakta", en: "Which street this trade is on", ru: "На какой улице это ремесло", ar: "في أي شارع هذه المهنة" },
  groupMeta: { tr: "%s kategori · %s dükkân", en: "%s categories · %s shops", ru: "%s категорий · %s магазинов", ar: "%s فئة · %s متجر" },
  subMeta: { tr: "%s alt kategori", en: "%s sub-categories", ru: "%s подкатегорий", ar: "%s فئة فرعية" },
  shopCount: { tr: "%s dükkân", en: "%s shops", ru: "%s магазинов", ar: "%s متجرًا" },
  street: { tr: "Sokak", en: "Street", ru: "Улица", ar: "شارع" },
  shopsHere: { tr: "Bu sokakta", en: "On this street", ru: "На этой улице", ar: "في هذا الشارع" },
  hoursLbl: { tr: "Sokak saatleri", en: "Street hours", ru: "Часы улицы", ar: "ساعات الشارع" },
  hoursVal: { tr: "%s – %s", en: "%s – %s", ru: "%s – %s", ar: "%s – %s" },
  inside: { tr: "Çarşı içi", en: "Inside the bazaar", ru: "Внутри базара", ar: "داخل السوق" },
  outside: { tr: "Çarşı dışı hat", en: "Outside the bazaar", ru: "Снаружи базара", ar: "خارج السوق" },
  wWide: { tr: "Geniş cadde", en: "Wide street", ru: "Широкая улица", ar: "شارع واسع" },
  wMedium: { tr: "Orta genişlik", en: "Medium width", ru: "Средняя ширина", ar: "عرض متوسط" },
  wNarrow: { tr: "Dar sokak — el arabası zor geçer", en: "Narrow lane — hard for handcarts", ru: "Узкий переулок", ar: "زقاق ضيق" },
  neighbors: { tr: "Komşu sokaklar", en: "Neighbouring streets", ru: "Соседние улицы", ar: "شوارع مجاورة" },
  gToday: { tr: "Bugün", en: "Today", ru: "Сегодня", ar: "اليوم" },
  gTomorrow: { tr: "Yarın", en: "Tomorrow", ru: "Завтра", ar: "غدًا" },
  gWeek: { tr: "Bu hafta", en: "This week", ru: "На этой неделе", ar: "هذا الأسبوع" },
  gLater: { tr: "Sonrası", en: "Later", ru: "Позже", ar: "لاحقًا" },
  gPast: { tr: "Geçti", en: "Past", ru: "Прошло", ar: "منتهٍ" },
  evCount: { tr: "%s etkinlik", en: "%s events", ru: "%s событий", ar: "%s نشاطًا" },
  evSub: { tr: "Çarşıda bu haftanın programı", en: "This week in the bazaar", ru: "Программа недели", ar: "برنامج الأسبوع" },
  evAdd: { tr: "Rotaya ekle", en: "Add to route", ru: "В маршрут", ar: "أضف إلى المسار" },
  evIn: { tr: "Rotada", en: "In route", ru: "В маршруте", ar: "في المسار" },
  evRemove: { tr: "Çıkar", en: "Remove", ru: "Убрать", ar: "إزالة" },
  evPlanTitle: { tr: "Rotandaki etkinlikler", en: "Events on your route", ru: "События в маршруте", ar: "أنشطة مسارك" },
  // M5 · gün takvimi
  dayTitle: { tr: "Gününüz", en: "Your day", ru: "Ваш день", ar: "يومك" },
  dayNote: { tr: "Duraklar, etkinlikler ve randevular tek çizgide. Çakışma varsa burada görünür.", en: "Stops, events and appointments on one line. Clashes show up here.", ru: "Остановки, события и встречи на одной линии.", ar: "المحطات والأنشطة والمواعيد على خط واحد." },
  dayStop: { tr: "%s. durak", en: "Stop %s", ru: "Остановка %s", ar: "المحطة %s" },
  dayEvent: { tr: "Etkinlik", en: "Event", ru: "Событие", ar: "نشاط" },
  dayAppt: { tr: "Randevu", en: "Appointment", ru: "Встреча", ar: "موعد" },
  clashTitle: { tr: "Gününüzde çakışma var", en: "Your day has a clash", ru: "В вашем дне есть накладка", ar: "يومك فيه تعارض" },
  clashBody: { tr: "%s öğe aynı saate düşüyor. Randevuyu kaydırın ya da durağı listeden çıkarın.", en: "%s items overlap. Move the appointment or drop a stop.", ru: "%s элементов пересекаются.", ar: "%s عناصر متعارضة." },
  clashRow: { tr: "Öncekiyle çakışıyor", en: "Overlaps the previous one", ru: "Пересекается с предыдущим", ar: "يتعارض مع السابق" },
  apFormTitle: { tr: "Randevu ekleyin", en: "Add an appointment", ru: "Добавить встречу", ar: "أضف موعدًا" },
  apTimePh: { tr: "14:30", en: "14:30", ru: "14:30", ar: "14:30" },
  apTitlePh: { tr: "Örn. Numune teslimı · Emre Aksesuar", en: "e.g. Sample pickup · Emre", ru: "Напр. образец", ar: "مثلًا استلام عينة" },
  apWherePh: { tr: "Nerede (isteğe bağlı)", en: "Where (optional)", ru: "Где (необяз.)", ar: "أين (اختياري)" },
  apAdd: { tr: "Takvime ekle", en: "Add to day", ru: "Добавить", ar: "أضف لليوم" },
  apAdded: { tr: "Randevu takviminize eklendi", en: "Appointment added to your day", ru: "Встреча добавлена", ar: "أُضيف الموعد" },
  apNeedTitle: { tr: "Randevuya bir ad verin", en: "Name the appointment", ru: "Укажите название", ar: "سمِّ الموعد" },
  apNeedTime: { tr: "Saati 14:30 gibi yazın", en: "Write the time like 14:30", ru: "Время в формате 14:30", ar: "اكتب الوقت مثل 14:30" },
  eta: { tr: "≈ %s'de burada", en: "≈ arrive %s", ru: "≈ прибытие %s", ar: "≈ الوصول %s" },
  endsAt: { tr: "Plan ≈ %s'de biter", en: "Plan ends ≈ %s", ru: "План завершится ≈ %s", ar: "تنتهي الخطة ≈ %s" },
  riskTag: { tr: "Varmadan kapanıyor", en: "Closes before you arrive", ru: "Закроется до прихода", ar: "يغلق قبل وصولك" },
  tightTag: { tr: "Kapanışa %s dk", en: "%s min before closing", ru: "%s мин до закрытия", ar: "%s دقيقة قبل الإغلاق" },
  riskTitle: { tr: "Sıra sorunu", en: "Ordering problem", ru: "Проблема порядка", ar: "مشكلة في الترتيب" },
  riskBody: { tr: "%s durak siz varmadan kapanıyor. Onları öne alın ya da yarına bırakın.", en: "%s stops close before you get there. Move them earlier or leave them for tomorrow.", ru: "%s остановок закроется до вашего прихода.", ar: "%s محطة تغلق قبل وصولك." },
  fridayTitle: { tr: "Cuma namazı arası", en: "Friday prayer break", ru: "Пятничный перерыв", ar: "فترة صلاة الجمعة" },
  fridayBody: { tr: "12:30–13:15 arası çoğu dükkân kapalı. Planınız bu aralığa denk geliyor.", en: "Most shops close between 12:30 and 13:15. Your plan runs through that window.", ru: "С 12:30 до 13:15 большинство лавок закрыто.", ar: "معظم المتاجر مغلقة بين 12:30 و13:15." },
  cargoTitle: { tr: "Kargo son kabul 16:00", en: "Cargo cut-off 16:00", ru: "Приём груза до 16:00", ar: "آخر قبول للشحن 16:00" },
  cargoBody: { tr: "Planınız %s'de bitiyor — bugün kargoya yetişmez.", en: "Your plan ends at %s — too late for today's cargo.", ru: "План заканчивается в %s — на сегодняшний груз не успеть.", ar: "تنتهي خطتك في %s — متأخر على شحنة اليوم." },
  tmrTitle: { tr: "Çarşı bugün kapandı", en: "The bazaar has closed for today", ru: "Базар закрыт на сегодня", ar: "أغلق السوق لهذا اليوم" },
  tmrBody: { tr: "Plan yarın sabah 09:30 başlangıcıyla kuruldu.", en: "The plan is built for a 09:30 start tomorrow.", ru: "План построен на завтра с 09:30.", ar: "بُنيت الخطة لبداية 09:30 غدًا." },
  coverage: { tr: "%s / %s kalem bulundu", en: "%s of %s items located", ru: "Найдено %s из %s", ar: "%s من %s بندًا" },
  stCoverage: { tr: "Kapsama", en: "Coverage", ru: "Покрытие", ar: "التغطية" },
  stStops: { tr: "Durak sayısı", en: "Stops", ru: "Остановки", ar: "المحطات" },
  stWalk: { tr: "Yürüyüş", en: "Walking", ru: "Пешком", ar: "سيرًا" },
  stopCount: { tr: "%s durak", en: "%s stops", ru: "%s остановок", ar: "%s محطة" },
  walkTotal: { tr: "≈ %s dk yürüyüş", en: "≈ %s min walking", ru: "≈ %s мин пешком", ar: "≈ %s دقيقة سيرًا" },
  totalLabel: { tr: "Liste toplamı · hedef fiyatla", en: "List total · at target prices", ru: "Итог списка · по целевым ценам", ar: "إجمالي القائمة · بأسعار مستهدفة" },
  missingNote: { tr: "%s kalemde hedef fiyat yok — toplama girmedi.", en: "%s items have no target price — not counted.", ru: "У %s позиций нет целевой цены.", ar: "%s بندًا بلا سعر مستهدف." },
  rateNote: { tr: "Kurlar tahminidir. Çarşıdaki döviz bürosu ve dükkân kuru farklı olabilir.", en: "Rates are indicative. Exchange offices and shops quote their own.", ru: "Курсы ориентировочные.", ar: "الأسعار تقديرية." },
  kCat: { tr: "Kategori", en: "Category", ru: "Категория", ar: "فئة" },
  kShop: { tr: "Dükkân", en: "Shop", ru: "Магазин", ar: "متجر" },
  kStreet: { tr: "Sokak", en: "Street", ru: "Улица", ar: "شارع" },
  kHan: { tr: "Han", en: "Han", ru: "Хан", ar: "خان" },
  kProduct: { tr: "Ürün", en: "Ürün", ru: "Товар", ar: "منتج" },
  kDoor: { tr: "Kapı no %s", en: "Door no %s", ru: "Дверь № %s", ar: "باب رقم %s" },
  kPhone: { tr: "Telefon", en: "Phone", ru: "Телефон", ar: "هاتف" },
  secWork: { tr: "İşlerim", en: "My work", ru: "Мои дела", ar: "أعمالي" },
  tabReq: { tr: "Taleplerim", en: "My requests", ru: "Мои запросы", ar: "طلباتي" },
  tabCmp: { tr: "Teklif karşılaştırma", en: "Compare offers", ru: "Сравнение предложений", ar: "مقارنة العروض" },
  tabSaved: { tr: "Kayıtlı dükkânlar", en: "Saved shops", ru: "Сохранённые магазины", ar: "متاجر محفوظة" },
  tabNotif: { tr: "Bildirimler", en: "Notifications", ru: "Уведомления", ar: "الإشعارات" },
  reqTitle: { tr: "Taleplerim", en: "My requests", ru: "Мои запросы", ar: "طلباتي" },
  reqSub: { tr: "Aramada karşılığı olmayanı yazın; HAN uygun dükkânlara iletir, teklifler burada birikir.", en: "Write what search cannot find; HAN passes it to the right shops and offers land here.", ru: "Опишите то, чего нет в поиске — HAN передаст магазинам, предложения появятся здесь.", ar: "اكتب ما لا يجده البحث؛ يوصله HAN إلى المتاجر وتتجمع العروض هنا." },
  cmpTitle: { tr: "Teklif karşılaştırma", en: "Compare offers", ru: "Сравнение предложений", ar: "مقارنة العروض" },
  cmpSub: { tr: "Ara sonuçlarında işaretlediğiniz 2–5 dükkânı ya da alım listesindeki bir kalemi yan yana görün: birim fiyat, minimum, kademe, teslim, kargo, tax-free, toplam.", en: "See the 2–5 shops you ticked in search results, or one buying-list item, side by side: unit price, minimum, tiers, lead time, shipping, tax-free, total.", ru: "Отмеченные в поиске 2–5 магазинов или одна позиция списка покупок рядом: цена, минимум, уровни, срок, доставка, tax-free, итог.", ar: "المتاجر التي حدّدتها في نتائج البحث (٢–٥) أو بند من قائمة الشراء جنبًا إلى جنب: السعر والحد الأدنى والشرائح والتسليم والشحن والإعفاء والإجمالي." },
  savedTitle: { tr: "Kayıtlı dükkânlar", en: "Saved shops", ru: "Сохранённые магазины", ar: "متاجر محفوظة" },
  savedSub: { tr: "Çevrimdışı da açılır; rota kurarken buradan başlayın.", en: "They open offline too; start your route from here.", ru: "Открываются и офлайн; начните маршрут отсюда.", ar: "تُفتح دون اتصال؛ ابدأ مسارك من هنا." },
  notifTitle: { tr: "Bildirimler", en: "Notifications", ru: "Уведомления", ar: "الإشعارات" },
  notifSub: { tr: "Teklifler, kampanyalar ve çarşı duyuruları.", en: "Offers, campaigns and bazaar announcements.", ru: "Предложения, акции и объявления базара.", ar: "العروض والحملات وإعلانات السوق." },
  noReqTitle: { tr: "Henüz talep bırakmadınız", en: "No requests yet", ru: "Запросов пока нет", ar: "لا طلبات بعد" },
  noReqBody: { tr: "Aradığınızı bulamadığınızda talep bırakın; uygun dükkânlar size fiyat verir.", en: "When search comes up empty, leave a request and the right shops quote you.", ru: "Если поиск пуст — оставьте запрос, магазины предложат цену.", ar: "إذا خلا البحث، اترك طلبًا وستسعّر لك المتاجر." },
  newReq: { tr: "Yeni talep", en: "New request", ru: "Новый запрос", ar: "طلب جديد" },
  newReqSub: { tr: "Ne, ne kadar, ne zamana kadar ve kime — teklifleri doğrulanmış numaranıza yönlendiririz.", en: "What, how much, by when and to whom — offers are routed to your verified number.", ru: "Что, сколько, до когда и кому — предложения придут на подтверждённый номер.", ar: "ماذا وكم ومتى ولمن — تُوجَّه العروض إلى رقمك الموثّق." },
  reqWhat: { tr: "Ne arıyorsunuz?", en: "What do you need?", ru: "Что нужно?", ar: "ماذا تحتاج؟" },
  reqQty: { tr: "Adet", en: "Qty", ru: "Кол-во", ar: "الكمية" },
  reqPhone: { tr: "Telefon", en: "Phone", ru: "Телефон", ar: "الهاتف" },
  sendReq: { tr: "Talebi gönder", en: "Send the request", ru: "Отправить запрос", ar: "أرسل الطلب" },
  eUrun: { tr: "Ne aradığınızı yazın", en: "Write what you need", ru: "Укажите, что нужно", ar: "اكتب ما تحتاجه" },
  reqSent: { tr: "Talebiniz iletildi", en: "Your request was sent", ru: "Запрос отправлен", ar: "أُرسل طلبك" },
  leaveReq: { tr: "Talep bırakın", en: "Leave a request", ru: "Оставить запрос", ar: "اترك طلبًا" },
  offers: { tr: "Gelen teklifler", en: "Offers received", ru: "Полученные предложения", ar: "العروض الواردة" },
  waiting: { tr: "Teklif bekleniyor", en: "Waiting for offers", ru: "Ожидание предложений", ar: "بانتظار العروض" },
  waitingBody: { tr: "Dükkânlara iletildi. İlk yanıtlar genelde birkaç saniyede gelir.", en: "Passed to the shops. First answers usually arrive within seconds.", ru: "Передано магазинам. Первые ответы обычно приходят за секунды.", ar: "أُرسل إلى المتاجر. تصل أول الردود عادة في ثوانٍ." },
  bestOffer: { tr: "En uygun teklif", en: "Best offer", ru: "Лучшее предложение", ar: "أفضل عرض" },
  best: { tr: "En uygun", en: "Best value", ru: "Выгоднее", ar: "الأفضل" },
  accept: { tr: "Kabul et", en: "Accept", ru: "Принять", ar: "قبول" },
  agreed: { tr: "Anlaşıldı", en: "Agreed", ru: "Договорились", ar: "تم الاتفاق" },
  openShop: { tr: "Dükkânı aç", en: "Open shop", ru: "Открыть магазин", ar: "افتح المتجر" },
  compare: { tr: "Karşılaştırmaya götür", en: "Take me to compare", ru: "К сравнению", ar: "إلى المقارنة" },
  pickReq: { tr: "Bir talep seçin", en: "Pick a request", ru: "Выберите запрос", ar: "اختر طلبًا" },
  pickReqBody: { tr: "Soldaki listeden bir talebe dokunun; gelen teklifler burada karşılaştırılır.", en: "Tap a request on the left; its offers are compared here.", ru: "Выберите запрос слева — предложения сравнятся здесь.", ar: "اختر طلبًا من اليسار؛ تُقارن عروضه هنا." },
  cmpEmpty: { tr: "Karşılaştıracak kalem yok", en: "Nothing to compare", ru: "Нечего сравнивать", ar: "لا شيء للمقارنة" },
  cmpEmptyBody: { tr: "İki yol var: Ara sonuçlarında dükkânları işaretleyip “Seçtiklerimi karşılaştır”a basın, ya da Plan sekmesindeki alım listesine bir kalem ekleyin.", en: "Two ways: tick shops in the search results and press “Compare my picks”, or add a line to the buying list on the Plan tab.", ru: "Два пути: отметьте магазины в результатах поиска или добавьте позицию в список покупок.", ar: "طريقان: حدّد المتاجر في نتائج البحث، أو أضف بندًا إلى قائمة الشراء." },
  cmpNote: { tr: "Toplam, adet kademeye ulaşıyorsa kademeli fiyattan hesaplanır. Kargo ve gümrük ayrıdır.", en: "Totals use tiered pricing when the quantity reaches a tier. Shipping and customs are separate.", ru: "Итог считается по уровню, если количество его достигает. Доставка и таможня отдельно.", ar: "يُحسب الإجمالي بالسعر المتدرج عند بلوغ الشريحة. الشحن والجمارك منفصلان." },
  noSaved: { tr: "Kayıtlı dükkân yok", en: "No saved shops", ru: "Нет сохранённых магазинов", ar: "لا متاجر محفوظة" },
  noSavedBody: { tr: "Bir dükkân detayında “Kaydet”e dokunun; burada toplanır ve çevrimdışı açılır.", en: "Tap “Save” in a shop's detail; they gather here and open offline.", ru: "Нажмите «Сохранить» в карточке магазина.", ar: "اضغط «حفظ» في تفاصيل المتجر." },
  routeTitle: { tr: "Yol tarifi", en: "Directions", ru: "Маршрут", ar: "الإرشادات" },
  routeTotal: { tr: "%s adım · ≈ %s dk", en: "%s steps · ≈ %s min", ru: "%s шагов · ≈ %s мин", ar: "%s خطوة · ≈ %s دقيقة" },
  minWord: { tr: "%s dk", en: "%s min", ru: "%s мин", ar: "%s دقيقة" },
  arrive: { tr: "Vardınız", en: "You have arrived", ru: "Вы на месте", ar: "لقد وصلت" },
  hanTitle: { tr: "Han", en: "Han", ru: "Хан", ar: "خان" },
  hanFloorCount: { tr: "%s kat", en: "%s floors", ru: "этажей: %s", ar: "%s طابق" },
  hanFloor: { tr: "%s. kat", en: "Floor %s", ru: "%s этаж", ar: "الطابق %s" },
  hanGround: { tr: "Zemin", en: "Ground", ru: "Первый", ar: "الأرضي" },
  hanEmptyFloor: { tr: "Bu katta kayıtlı dükkân yok.", en: "No listed shops on this floor.", ru: "На этом этаже нет магазинов.", ar: "لا متاجر مسجلة في هذا الطابق." },
  secTools: { tr: "Araçlar", en: "Tools", ru: "Инструменты", ar: "الأدوات" },
  toolFx: { tr: "Döviz çevirici", en: "Currency converter", ru: "Конвертер валют", ar: "محوّل العملات" },
  toolTax: { tr: "Tax-free", en: "Tax-free", ru: "Tax-free", ar: "إعفاء ضريبي" },
  toolNear: { tr: "Yakınımda", en: "Nearby", ru: "Рядом", ar: "بالقرب مني" },
  toolNearSub: { tr: "Kargo, döviz, emanet ve diğer pratik noktalar.", en: "Cargo, exchange, storage and other practical points.", ru: "Карго, обмен валют, хранение и другие точки.", ar: "الشحن والصرافة والتخزين ونقاط عملية أخرى." },
  toolShip: { tr: "Nakliye ve gönderim", en: "Shipping & freight", ru: "Доставка и фрахт", ar: "الشحن والنقل" },
  toolCulture: { tr: "Çarşı görgüsü", en: "Bazaar etiquette", ru: "Этикет базара", ar: "آداب السوق" },
  toolEmergency: { tr: "Acil durum", en: "Emergency", ru: "Экстренная помощь", ar: "الطوارئ" },
  toolReport: { tr: "Sorun bildir", en: "Report a problem", ru: "Сообщить о проблеме", ar: "الإبلاغ عن مشكلة" },
  poiEmpty: { tr: "Bu türde nokta yok", en: "No points of this kind", ru: "Нет таких точек", ar: "لا نقاط من هذا النوع" },
  poiFrom: { tr: "Yürüme mesafesinde", en: "Within walking distance", ru: "В пределах пешей досягаемости", ar: "على مسافة قريبة سيرًا" }
};

/**
 * Look a string up and fill its `%s` placeholders.
 *
 * Falls back to Turkish, never to the key: a missing translation should read
 * as Turkish text, not as `secDiscover`.
 */
function make(table: Record<string, CopyEntry>) {
  return (lang: Lang, key: string, a?: string | number | null, b?: string | number | null): string => {
    const entry = table[key];
    let s = (entry && (entry[lang] || entry.tr)) || "";
    if (a != null) s = s.replace("%s", String(a));
    if (b != null) s = s.replace("%s", String(b));
    return s;
  };
}

export const W = make(W_COPY);
export const F = make(F_COPY);
